version : '3'
services:
  spring-blog-db:
    container_name: spring-blog-db
    image: postgres:10.6-alpine
    environment:
      - 'POSTGRES_DB=spring_blog_db'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'